spring.application.name=preptrack

# Switch to In-Memory H2 Database for smooth cloud deployment
spring.datasource.url=jdbc:h2:mem:preptrackdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Render handles dynamic ports, but let's keep it safe for Spring Boot
server.port=9090
spring.h2.console.enabled=true